[pytest]
addopts = --verbosity=1 --ignore planemo/commands/cmd_test.py
markers =
    installed_galaxy: tests requiring a package-installed Galaxy runtime managed by Gravity
    installed_galaxy_toolshed: installed Galaxy tests that require the external Tool Shed
    tests_galaxy_branch: test against a specific Galaxy branch
