#!/bin/sh

CWD="$( pwd -P )"

PLANEMO_BIN="${PLANEMO_BIN:-planemo}"
PLANEMO_ARGS="${PLANEMO_ARGS:-}"

VERBOSE_ARG="--verbose"
USE_CONTAINER=1

# Pop args meant for common_startup.sh                                                     
while :
do
    case "$1" in
        --version|--help)
             $PLANEMO_BIN "$1"
             exit $?
             ;;
        --no-container)
             USE_CONTAINER=0
             shift
             ;;
        --quiet)
             VERBOSE_ARG=""
             shift
             ;; 
        --basedir*)
             BASEDIR=`echo $1 | sed -e 's/^[^=]*=//g'`
             #echo `pwd`
             #cd "$BASEDIR"
             shift
             ;;
        "")
            break
            ;;
        *)
            PLANEMO_ARGS="$PLANEMO_ARGS $1"
            shift
            ;;
    esac
done

# TODO: Do something with USE_CONTAINER
if [ -n USE_CONTAINER ];
then
    PLANEMO_ARGS="$PLANEMO_ARGS --docker --cwl --output_json $CWD/outputs.json"
fi

# echo "$PLANEMO_ARGS"

"$PLANEMO_BIN" $VERBOSE_ARG run $PLANEMO_ARGS >planemo_run.log 2>&1

cat "$CWD/outputs.json"
