#!/usr/bin/env python
"""Export dependency files from project metadata and the committed uv lock."""

import argparse
import subprocess
from pathlib import Path

import tomlkit
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
HEADER = "# Generated by scripts/update_dependencies.py; edit pyproject.toml and refresh the lock.\n"


def requirement_key(requirement):
    parsed = Requirement(requirement)
    return (
        canonicalize_name(parsed.name),
        str(parsed.specifier),
        tuple(sorted(parsed.extras)),
        str(parsed.marker) if parsed.marker else None,
    )


def locked_requirement(entry):
    extras = "[" + ",".join(entry["extras"]) + "]" if entry.get("extras") else ""
    marker = " ; " + entry["marker"] if entry.get("marker") else ""
    return entry["name"] + extras + entry.get("specifier", "") + marker


def dependency_files(root=ROOT):
    project = tomlkit.loads((root / "pyproject.toml").read_text())
    groups = project["dependency-groups"]

    def expand(name):
        for entry in groups[name]:
            if isinstance(entry, str):
                yield entry
            else:
                yield from expand(entry["include-group"])

    lock = tomlkit.loads((root / "uv.lock").read_text())
    metadata = next(package for package in lock["package"] if package["name"] == "planemo")["metadata"]
    declared = {requirement_key(entry) for entry in project["project"]["dependencies"]}
    locked = {requirement_key(locked_requirement(entry)) for entry in metadata["requires-dist"]}
    if declared != locked or project["project"]["requires-python"] != lock["requires-python"]:
        raise ValueError("Runtime requirements changed; run uv lock and regenerate dependency files")
    for name in groups:
        declared_group = {requirement_key(entry) for entry in expand(name)}
        locked_group = {requirement_key(locked_requirement(entry)) for entry in metadata["requires-dev"].get(name, [])}
        if declared_group != locked_group:
            raise ValueError(f"Dependency group {name} changed; run uv lock and regenerate dependency files")

    pins = subprocess.check_output(
        [
            "uv",
            "export",
            "--frozen",
            "--no-default-groups",
            "--no-emit-project",
            "--no-hashes",
            "--no-header",
            "--no-annotate",
        ],
        cwd=root,
        text=True,
    )
    return {
        "requirements.txt": HEADER + "\n".join(project["project"]["dependencies"]) + "\n",
        "dev-requirements.txt": HEADER + "\n".join(dict.fromkeys(expand("dev"))) + "\n",
        "requirements-cli.txt": HEADER + pins,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ")
    args = parser.parse_args()
    stale = []
    for name, content in dependency_files().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.write_text(content)
    if stale:
        parser.exit(1, "Regenerate dependency files: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
